apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-agent
  namespace: observability
  labels:
    app: otel-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-agent
  labels:
    app: otel-agent
rules:
  # Pod and node discovery
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
      - nodes/stats
      - nodes/proxy
      - services
      - endpoints
      - events
      - replicationcontrollers
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["get", "list", "watch"]

  # Workload discovery
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]

  # Job discovery
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # HPA discovery
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]

  # Ingress discovery
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  # Metrics endpoints
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-agent
  labels:
    app: otel-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-agent
subjects:
  - kind: ServiceAccount
    name: otel-agent
    namespace: observability
