apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-mortgage-inference
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - nginx-config.yaml
  - demo-html.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
