apiVersion: v1
kind: Service
metadata:
  name: mortgage-inference
  namespace: demo-mortgage-inference
  labels:
    app: mortgage-inference
spec:
  type: ClusterIP
  selector:
    app: mortgage-inference
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mortgage-inference-nb
  namespace: demo-mortgage-inference
  labels:
    app: mortgage-inference
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "0"
spec:
  type: LoadBalancer
  selector:
    app: mortgage-inference
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
